parameters:
    ezplatform.cron.registry.cronjobs.class: EzSystems\EzPlatformCronBundle\Registry\CronJobsRegistry
    ezplatform.console.command.run.class: EzSystems\EzPlatformCronBundle\Command\CronRunCommand

services:
    ezplatform.cron.registry.cronjobs:
        class: '%ezplatform.cron.registry.cronjobs.class%'
        arguments:
            - '%kernel.environment%'
            - '@ezpublish.siteaccess'

    ezplatform.console.command.run:
        class: '%ezplatform.console.command.run.class%'
        tags:
            - { name: console.command }
            - { name: monolog.logger, channel: cronjob }
