parameters:
    ezplatform.cron.registry.cronjobs.class: EzSystems\EzPlatformCronBundle\Registry\CronJobsRegistry

services:
    ezplatform.cron.registry.cronjobs:
        class: '%ezplatform.cron.registry.cronjobs.class%'
        arguments:
            - '%kernel.environment%'
            - '@ezpublish.siteaccess'

    ezplatform.console.command.run:
        class: EzSystems\EzPlatformCronBundle\Command\CronRunCommand
        arguments:
            $logger: '@monolog.logger.cronjob'
        tags:
            - { name: console.command }
