parameters:
    ezplatform.cron.registry.cronjobs.class: EzSystems\CronBundle\Registry\CronJobsRegistry

services:
    ezplatform.cron.registry.cronjobs:
        class: '%ezplatform.cron.registry.cronjobs.class%'
        arguments:
            - '%kernel.environment%'
